comment:
  behavior: default
  hide_project_coverage: false
  layout: diff, flags, files
  require_base: true
  require_changes:
    - 1
  require_head: true
coverage:
  ignore:
    - "api/src/test/java/com/coze/openapi/client/**"
  status:
    project:
      default:
        base: auto
        paths:
          - (?s:coze\-java\-sdk/api/.*)\Z
        target: 90.0
        threshold: 90.0