name: CI

on:
  push:
    branches:
     - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test (Java ${{ matrix.java-version }} on ${{ matrix.os-label }})
    strategy:
      fail-fast: false
      matrix:
        java-version: [ "8", "11", "17" ]
        os: [ "ubuntu-latest" ]
        os-label: [ "Ubuntu" ]
        include:
          - { java-version: "11", os: "windows-latest", os-label: "Windows" }
          - { java-version: "11", os: "macos-latest", os-label: "macOS" }

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Code style check
        run: mvn spotless:check

      - name: Build and Test with Coverage
        run: |
          mvn -pl api clean test-compile
          mvn -pl api test jacoco:report

      - name: Debug Test Results (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "Test Results:"
          find . -name "TEST-*.xml" -exec cat {} \;
          echo "JaCoCo Report Location:"
          ls -la api/target/site/jacoco/
          
      - name: Debug Test Results (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Test Results:"
          Get-ChildItem -Recurse -Filter "TEST-*.xml" | Get-Content
          echo "JaCoCo Report Location:"
          Get-ChildItem -Path "api\target\site\jacoco" -Force
          
      - name: Generate JaCoCo Report
        run: mvn -pl api jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./api/target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-